name: builds on Linux

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ develop ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  #workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: Ubuntu-24.04
            
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: update package index
        run: sudo apt update

      - name: Install accendino
        run: python3 -m pip install accendino==0.5.10a2

      - name: Test build with Qt5
        run: accendino --prefix=/tmp/qfreerdp_platform --targets=qfreerdp_platform-qt5 --debug ci/qfreerdp_platform.accendino

      - name: Test build with Qt6
        run: accendino --prefix=/tmp/qfreerdp_platform --targets=qfreerdp_platform-qt6 --debug ci/qfreerdp_platform.accendino

